version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telebot-container
    restart: unless-stopped
    
    env_file:
      - .env
    volumes:
      - ./persistence:/app/persistence
    